### ISSUE TITLE
Index not in list error when evaluating models zero-shot

### ISSUE THREAD

**Issue by rtaori** [princeton-nlp/LM-BFF#7]
Hi,

I would like to evaluate a few different BERT models zero-shot on MNLI, SNLI, QNLI, and RTE. As such, I am running this following command, for example:
```
TYPE=prompt TASK=MNLI BS=2 LR=1e-5 SEED=42 K=16 MODEL=roberta-large bash run_experiment.sh "--no_train"
```

Unfortunately, this gives me a somewhat cryptic error message:
```
Traceback (most recent call last):
  File "run.py", line 632, in <module>
    main()
  File "run.py", line 465, in main
    FewShotDataset(data_args, tokenizer=tokenizer, mode="test", use_demo=("demo" in model_args.few_shot_type))
  File "/sailhome/rtaori/zero-shot-generalization/LM-BFF/src/dataset.py", line 456, in __init__
    self.features.append(self.convert_fn(
  File "/sailhome/rtaori/zero-shot-generalization/LM-BFF/src/dataset.py", line 575, in convert_fn
    inputs = tokenize_multipart_input(
  File "/sailhome/rtaori/zero-shot-generalization/LM-BFF/src/dataset.py", line 243, in tokenize_multipart_input
    mask_pos = [input_ids.index(tokenizer.mask_token_id)]
ValueError: 50264 is not in list
```
A similar error occurs for SNLI, QNLI, and RTE. 

Do you have any advice on how to deal with this? Any help would be much appreciated!

Thanks in advance,
Rohan

**Comment by gaotianyu1350** [comment]
Hi Rohan, sorry for the trouble! This is caused by a bug in the training script (it did not load task-specific parameters before). Now this is fixed. Thanks for letting us know!

Tianyu

**Comment by rtaori** [comment]
Great! Thank you so much @gaotianyu1350 !

**Comment by shi-kejian** [comment]
Hi,
Thanks again for the great work. 

Today I actually encountered the same error, when testing a model prompt-tuned on SST-2 directly on imdb movie review dataset, by replacing the dev.tsv in /original with the imdb dataset. As you mentioned in the paper and in issue #14 . 

What I did: 
1. prompt tune a model ckpt on SST-2, and save the model
2. replace the data/original/SST-2/dev.tsv with my own imdb dataset, and format it correctly 
3. run tools/generate_k_shot.py again. The data/k-shot/SST-2/test.tsv turns to imdb. 
4. load the model in 1) and put --no_train, --do_predict, and other necessary flags to zero-shot on the imdb dataset. 
Error occurs. 
Traceback (most recent call last):
  File "run.py", line 628, in <module>
    main()
  File "run.py", line 466, in main
    if training_args.do_predict
  File "/home/yb1025/Research/ML_2/robustness/LM-BFF/src/dataset.py", line 465, in __init__
    verbose=True if _ == 0 else False,
  File "/home/yb1025/Research/ML_2/robustness/LM-BFF/src/dataset.py", line 585, in convert_fn
    other_sent_limit=self.args.other_sent_limit,
  File "/home/yb1025/Research/ML_2/robustness/LM-BFF/src/dataset.py", line 243, in tokenize_multipart_input
    mask_pos = [input_ids.index(tokenizer.mask_token_id)]
ValueError: 50264 is not in list

Sorry for the inconvenience but do you happen to know what might went wrong? 

Many thanks.
